breadlist/breadlist/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('classifieds.urls')),
]

breadlist/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('classifieds.urls')),
]

classifieds/urls.py
from django.urls import path

from . import views

app_name = "classifieds"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:classified_id>', views.detail, name='detail'),
    path('create-classified/', views.create_classified, name='create_classified'),
    path('thanks/', views.thanks, name='thanks'),
    path('pages/<str:page_name>/', views.page, name='page'),
    path('regions/<region_id>', views.region, name='region'),
    path('provinces/<province_id>', views.province, name='province'),
    path('locales/<locale_id>/', views.locale_index, name='locale'),
    path('<locale_id>/<str:section>/', views.section_index, name='section'),
    path('<locale_id>/<str:section>/<str:subsection>', views.subsection_index, name='subsection'),
]

classifieds/models.py
from django.db import models
from django.utils import timezone

class Locale(models.Model):
    locale_name = models.CharField(max_length=200)
    abbreviation = models.CharField(max_length=8)
    province = models.ForeignKey('Province', on_delete=models.CASCADE)
    region = models.ForeignKey('Region', on_delete=models.CASCADE)
    def __str__(self):
        return self.locale_name

class Sublocale(models.Model):
    sublocale_name = models.CharField(max_length=200)
    abbreviation = models.CharField(max_length=8)
    province = models.ForeignKey('Province', on_delete=models.CASCADE)
    region = models.ForeignKey('Region', on_delete=models.CASCADE)
    parent_locale = models.ForeignKey('Locale', on_delete=models.CASCADE)
    def __str__(self):
        return self.abbreviation

class Province(models.Model):
    province_name = models.CharField(max_length=200)
    region = models.ForeignKey('Region', on_delete=models.CASCADE)
    def __str__(self):
        return self.province_name

class Region(models.Model):
    region_name = models.CharField(max_length=200)
    def __str__(self):
        return self.region_name

class Section(models.Model):
    section_name = models.CharField(max_length=200)
    def __str__(self):
        return self.section_name

class Subsection(models.Model):
    subsection_name = models.CharField(max_length=200)
    def __str__(self):
        return self.subsection_name

class Classified(models.Model):
    classified_title = models.CharField(max_length=200)
    classified_text = models.TextField()
    datetime_created = models.DateTimeField(auto_now=False, auto_now_add=True)
    locale = models.ForeignKey('Locale', on_delete=models.CASCADE)
    section = models.ForeignKey('Section', on_delete=models.CASCADE)
    subsection = models.ForeignKey('Subsection', on_delete=models.CASCADE)
    def __str__(self):
        return self.classified_title
    def was_created_recently(self):
        return self.datetime_created >= timezone.now() - datetime.timedelta(days=1)

class Page(models.Model):
    page_name = models.CharField(max_length=200)
    page_text = models.TextField()
    def __str__(self):
        return self.page_name

classifieds/forms.py
from django import forms
from django.db import models
from django.forms import ModelForm
from .models import Locale, Section, Subsection
from classifieds.models import Classified

class CreateClassifiedForm(ModelForm):
    class Meta:
        model = Classified
        fields = ['classified_title', 'classified_text', 'locale', 'section', 'subsection']

classifieds/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import loader
from .models import Classified, Page, Locale, Section, Subsection, Province, Region
from .forms import CreateClassifiedForm

def index(request):
    locale_list = Locale.objects.order_by('locale_name')
    section_list = Section.objects.order_by('pk')
    subsection_list = Subsection.objects.order_by('pk')
    page_list = Page.objects.order_by('pk')
    province_list = Province.objects.order_by('pk')
    region_list = Region.objects.order_by('pk')
    context = {
        'page_list': page_list,
        'locale_list': locale_list,
        'section_list': section_list,
        'subsection_list': subsection_list,
        'province_list': province_list,
        'region_list': region_list,
    }
    return render(request, 'classifieds/index.html', context)

def locale_index(request, locale_id):
    l = get_object_or_404(Locale, pk=locale_id)
    r = get_object_or_404(Region, pk=l.region_id)
    p = get_object_or_404(Province, pk=l.province_id)
    locale_list = Locale.objects.order_by('locale_name')
    section_list = Section.objects.order_by('pk')
    subsection_list = Subsection.objects.order_by('pk')
    page_list = Page.objects.order_by('pk')
    province_list = Province.objects.order_by('pk')
    region_list = Region.objects.order_by('pk')
    context = {
        'locale': l,
        'region': r,
        'province': p,
        'page_list': page_list,
        'locale_list': locale_list,
        'section_list': section_list,
        'subsection_list': subsection_list,
        'province_list': province_list,
        'region_list': region_list,
    }
    return render(request, 'classifieds/locale-index.html', context)

def section_index(request, locale_id, section):
    l = get_object_or_404(Locale, pk=locale_id)
    s = get_object_or_404(Section, section_name=section)
    section_classified_list = Classified.objects.filter(locale_id=locale_id).filter(section__section_name=section).order_by('datetime_created')
    locale_list = Locale.objects.order_by('locale_name')
    section_list = Section.objects.order_by('pk')
    subsection_list = Subsection.objects.order_by('pk')
    page_list = Page.objects.order_by('pk')
    province_list = Province.objects.order_by('pk')
    region_list = Region.objects.order_by('pk')
    context = {
        'locale': l,
        'section': section,
        'page_list': page_list,
        'locale_list': locale_list,
        'section_list': section_list,
        'subsection_list': subsection_list,
        'section_classified_list': section_classified_list,
        'province_list': province_list,
        'region_list': region_list,
    }
    return render(request, 'classifieds/section-index.html', context)

def subsection_index(request, locale_id, section, subsection):
    l = get_object_or_404(Locale, pk=locale_id)
    s = get_object_or_404(Section, section_name=section)
    ss = get_object_or_404(Subsection, subsection_name=subsection)
    subsection_classified_list = Classified.objects.filter(locale_id=locale_id).filter(section__section_name=section).filter(subsection__subsection_name=subsection).order_by('datetime_created')
    locale_list = Locale.objects.order_by('locale_name')
    section_list = Section.objects.order_by('pk')
    subsection_list = Subsection.objects.order_by('pk')
    page_list = Page.objects.order_by('pk')
    province_list = Province.objects.order_by('pk')
    region_list = Region.objects.order_by('pk')
    context = {
        'page_list': page_list,
        'locale': l,
        'section': s,
        'subsection': ss,
        'locale_list': locale_list,
        'section_list': section_list,
        'subsection_list': subsection_list,
        'subsection_classified_list': subsection_classified_list,
        'province_list': province_list,
        'region_list': region_list,
    }
    return render(request, 'classifieds/subsection-index.html', context)

def detail(request, classified_id):
    classified = get_object_or_404(Classified, pk=classified_id)
    l = get_object_or_404(Locale, pk=classified.locale_id)
    locale_list = Locale.objects.order_by('locale_name')
    section_list = Section.objects.order_by('pk')
    subsection_list = Subsection.objects.order_by('pk')
    page_list = Page.objects.order_by('pk')
    province_list = Province.objects.order_by('pk')
    region_list = Region.objects.order_by('pk')
    context = {
        'classified': classified,
        'locale': l,
        'locale_list': locale_list,
        'section_list': section_list,
        'subsection_list': subsection_list,
        'page_list': page_list,
        'province_list': province_list,
        'region_list': region_list,
    }
    return render(request, 'classifieds/detail.html', context)

def region(request, region_id):
    r = get_object_or_404(Region, pk=region_id)
    locale_list = Locale.objects.order_by('locale_name')
    section_list = Section.objects.order_by('pk')
    subsection_list = Subsection.objects.order_by('pk')
    page_list = Page.objects.order_by('pk')
    province_list = Province.objects.order_by('pk')
    province_list_sorted = Province.objects.filter(region_id=region_id).order_by('province_name')
    region_list = Region.objects.order_by('pk')
    context = {
        'region': r,
        'locale_list': locale_list,
        'section_list': section_list,
        'subsection_list': subsection_list,
        'page_list': page_list,
        'province_list': province_list,
        'region_list': region_list,
        'province_list_sorted': province_list_sorted,
    }
    return render(request, 'classifieds/region-index.html', context)

def province(request, province_id):
    p = get_object_or_404(Province, pk=province_id)
    locale_list = Locale.objects.order_by('locale_name')
    locale_list_sorted = Locale.objects.filter(province_id=province_id).order_by('locale_name')
    section_list = Section.objects.order_by('pk')
    subsection_list = Subsection.objects.order_by('pk')
    page_list = Page.objects.order_by('pk')
    province_list = Province.objects.order_by('pk')
    region_list = Region.objects.order_by('pk')
    context = {
        'province': p,
        'region': p.region,
        'locale_list': locale_list,
        'section_list': section_list,
        'subsection_list': subsection_list,
        'page_list': page_list,
        'province_list': province_list,
        'region_list': region_list,
        'locale_list_sorted': locale_list_sorted
    }
    return render(request, 'classifieds/province-index.html', context)

def page(request, page_name):
    page = get_object_or_404(Page, page_name=page_name)
    locale_list = Locale.objects.order_by('locale_name')
    section_list = Section.objects.order_by('pk')
    subsection_list = Subsection.objects.order_by('pk')
    page_list = Page.objects.order_by('pk')
    province_list = Province.objects.order_by('pk')
    region_list = Region.objects.order_by('pk')
    context = {
        'page': page,
        'locale_list': locale_list,
        'section_list': section_list,
        'subsection_list': subsection_list,
        'page_list': page_list,
        'province_list': province_list,
        'region_list': region_list,
    }
    return render(request, 'classifieds/page.html', context)

def thanks(request):
    locale_list = Locale.objects.order_by('locale_name')
    section_list = Section.objects.order_by('pk')
    subsection_list = Subsection.objects.order_by('pk')
    page_list = Page.objects.order_by('pk')
    province_list = Province.objects.order_by('pk')
    region_list = Region.objects.order_by('pk')
    context = {
        'locale_list': locale_list,
        'section_list': section_list,
        'subsection_list': subsection_list,
        'page_list': page_list,
        'province_list': province_list,
        'region_list': region_list,
    }
    return render(request, 'classifieds/thanks.html', context)

def create_classified(request):
    locale_list = Locale.objects.order_by('locale_name')
    section_list = Section.objects.order_by('pk')
    subsection_list = Subsection.objects.order_by('pk')
    page_list = Page.objects.order_by('pk')
    province_list = Province.objects.order_by('pk')
    region_list = Region.objects.order_by('pk')
    if request.method == 'POST':
        form = CreateClassifiedForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/thanks/')
    else:
        form = CreateClassifiedForm().as_ul()
        context = {
            'form': form,
            'locale_list': locale_list,
            'section_list': section_list,
            'subsection_list': subsection_list,
            'page_list': page_list,
            'province_list': province_list,
            'region_list': region_list,
        }
    return render(request, 'classifieds/create-classified.html', context)

classifieds/templates/classifieds/create-classified.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Breadlist: Create a Classified</title>{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'classifieds/style.css' %}">
  </head>
  <body>
    <header>
      <h2>Create a Classified</h2>
    </header>
    <nav>
      <img id="kropotkin" src="{% static "classifieds/images/kropotkin.jpg" %}" alt="the face of peter kropotkin done in a woodblock style"></img>
      <h1><a href="{% url 'classifieds:index' %}">Breadlist</a></h1>
      <ul>{% for p in page_list %}
        <li id={{ p }}><a href="{% url 'classifieds:page' p.page_name %}">{{ p }}</a></li>{% endfor %}
      </ul>
    </nav>
    <main>
      <form action="/create-classified/" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
      </form>
    </main>
    <aside>
      <ul>{% for r in region_list %}
        <li class="sidebar-locale"><a href="{% url 'classifieds:region' r %}">{{ r }}</a></li>{% endfor %}
      </ul>
    </aside>
    <footer>
      <ul>
        <li><a href="{% url 'classifieds:index' %}">back to index</a></li>
      </ul>
    </footer>
  </body>
</html>

classifieds/templates/classifieds/detail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{{ classified }}</title>{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'classifieds/style.css' %}">
  </head>
  <body>
    <header>
      <h1>{{ classified }}</h1>
    </header>
    <nav>
      <img id="kropotkin" src="{% static "classifieds/images/kropotkin.jpg" %}" alt="the face of peter kropotkin done in a woodblock style"></img>
      <h1><a href="{% url 'classifieds:index' %}">Breadlist</a></h1>
      <p><a href="{% url 'classifieds:create_classified' %}">create a classified</a></p>
      <ul>{% for page in page_list %}
        <li id={{ page }}><a href="{% url 'classifieds:page' page %}">{{ page }}</a></li>{% endfor %}}
      </ul>
    </nav>
    <main>
      <p>{{ classified.classified_text }}</p>
    </main>
    <aside>
      <ul>{% for r in region_list %}
        <li class="sidebar-locale"><a href="{% url 'classifieds:region' r.id %}">{{ r }}</a></li>{% endfor %}
      </ul>
    </aside>
    <footer>
      <ul>
        <li><a href="{% url 'classifieds:index' %}">breadlist</a></li>
        <li><a href="{% url 'classifieds:region' locale.region_id %}">breadlist/{{ locale.region }}</a></li>
        <li><a href="{% url 'classifieds:province' locale.province_id %}">breadlist/{{ locale.region }}/{{ locale.province }}</a></li>
        <li><a href="{% url 'classifieds:locale' locale.id %}">breadlist/{{ locale.region }}/{{ locale.province }}/{{ locale }}</a></li>
        <li><a href="{% url 'classifieds:section' locale.id classified.section %}">breadlist/{{ locale.region }}/{{ locale.province }}/{{ locale }}/{{ classified.section }}</a></li>
        <li><a href="{% url 'classifieds:subsection' classified.locale_id classified.section classified.subsection %}">breadlist/{{ locale.region }}/{{ locale.province }}/{{ classified.locale }}/{{ classified.section }}/{{ classified.subsection }}</a></li>
      </ul>
    </footer>
  </body>
</html>

classifieds/templates/classifieds/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Breadlist: Index</title>{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'classifieds/style.css' %}">
  </head>
  <body>
    <header>
      <h2>Index</h2>
    </header>
    <nav>
      <img id="kropotkin" src="{% static "classifieds/images/kropotkin.jpg" %}" alt="the face of peter kropotkin done in a woodblock style"></img>
      <h1><a href="{% url 'classifieds:index' %}">Breadlist</a></h1>
      <p><a href="{% url 'classifieds:create_classified' %}">create a classified</a></p>
      <ul>{% for p in page_list %}
        <li id={{ p }}><a href="{% url 'classifieds:page' p.page_name %}">{{ p }}</a></li>{% endfor %}
      </ul>
    </nav>
    <main>{% for r in region_list %}
      <section id="{{ r }}">
        <h3 class="region"><a href="{% url 'classifieds:region' r.id %}">{{ r }}</a></h3>
      </section>{% endfor %}
    </main>
    <aside>
      <ul>{% for r in region_list %}
        <li class="sidebar-locale"><a href="{% url 'classifieds:region' r.id %}">{{ r }}</a></li>{% endfor %}
      </ul>
    </aside>
  </body>
</html>

classifieds/templates/classifieds/locale-index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Breadlist Index: {{ locale_name }}</title>{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'classifieds/style.css' %}">
  </head>
  <body>
    <header>
      <h2>{{ locale }}</h2>
    </header>
    <nav>
      <img id="kropotkin" src="{% static "classifieds/images/kropotkin.jpg" %}" alt="the face of peter kropotkin done in a woodblock style"></img>
      <h1><a href="{% url 'classifieds:index' %}">Breadlist</a></h1>
      <p><a href="{% url 'classifieds:create_classified' %}">create a classified</a></p>
      <ul>{% for p in page_list %}
        <li id={{ p }}><a href="{% url 'classifieds:page' p.page_name %}">{{ p }}</a></li>{% endfor %}
      </ul>
    </nav>
    <main>
      {% for s in section_list %}
      <section class={{ s }}>
        <h3 class="section"><a href="{% url 'classifieds:section' locale.id s %}">{{ s }}</a></h3>
        <ul>
          {% for ss in subsection_list %}
          <li class="subsection"><a href="{% url 'classifieds:subsection' locale.id s ss %}">{{ ss }}</a></li>{% endfor %}
        </ul>
      </section>{% endfor %}
    </main>
    <aside>
      <ul>{% for r in region_list %}
        <li class="sidebar-locale"><a href="{% url 'classifieds:region' r.id %}">{{ r }}</a></li>{% endfor %}
      </ul>
    </aside>
    <footer>
      <ul>
        <li><a href="{% url 'classifieds:index' %}">breadlist</a></li>
        <li><a href="{% url 'classifieds:region' region.id %}">breadlist/{{ region }}</a></li>
        <li><a href="{% url 'classifieds:province' province.id %}">breadlist/{{ region }}/{{ province }}</a></li>
      </ul>
    </footer>
  </body>
</html>

classifieds/templates/classifieds/page.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{{ page }}</title>{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'classifieds/style.css' %}">
  </head>
  <body>
    <header>
      <h2>{{ page }}</h2>
    </header>
    <nav>
      <img id="kropotkin" src="{% static "classifieds/images/kropotkin.jpg" %}" alt="the face of peter kropotkin done in a woodblock style"></img>
      <h1><a href="{% url 'classifieds:index' %}">Breadlist</a></h1>
      <p><a href="{% url 'classifieds:create_classified' %}">create a classified</a></p>
      <ul>{% for page in page_list %}
        <li id={{ page }}><a href="{% url 'classifieds:page' page %}">{{ page }}</a></li>{% endfor %}
      </ul>
    </nav>
    <main>
      <p>{{ page.page_text }}</p>
    </main>
    <aside>
      <ul>{% for r in region_list %}
        <li class="sidebar-locale"><a href="{% url 'classifieds:region' r.id %}">{{ r }}</a></li>{% endfor %}
      </ul>
    </aside>
    <footer>
      <ul>
        <li><a href="{% url 'classifieds:index' %}">breadlist</a></li>
      </ul>
    </footer>
  </body>
</html>

classifieds/templates/classifieds/province-index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Breadlist: {{ province }}</title>{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'classifieds/style.css' %}">
  </head>
  <body>
    <header>
      <h2>{{ province }}</h2>
    </header>
    <nav>
      <img id="kropotkin" src="{% static "classifieds/images/kropotkin.jpg" %}" alt="the face of peter kropotkin done in a woodblock style"></img>
      <h1><a href="{% url 'classifieds:index' %}">Breadlist</a></h1>
      <p><a href="{% url 'classifieds:create_classified' %}">create a classified</a></p>
      <ul>{% for p in page_list %}
        <li id={{ p }}><a href="{% url 'classifieds:page' p.page_name %}">{{ p }}</a></li>{% endfor %}
      </ul>
    </nav>
    <main>{% for l in locale_list_sorted %}
      <section>
        <li><a href="{% url 'classifieds:locale' l.id %}">{{ l }}</a></li>
      </section>{% endfor %}
    </main>
    <aside>
      <ul>{% for r in region_list %}
        <li class="sidebar-locale"><a href="{% url 'classifieds:region' r.id %}">{{ r }}</a></li>{% endfor %}
      </ul>
    </aside>
    <footer>
      <ul>
        <li><a href="{% url 'classifieds:index' %}">breadlist</a></li>
        <li><a href="{% url 'classifieds:region' region.id %}">breadlist/{{ region }}</a></li>
      </ul>
    </footer>
  </body>
</html>

classifieds/templates/classifieds/region-index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Breadlist: {{ region }}</title>{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'classifieds/style.css' %}">
  </head>
  <body>
    <header>
      <h2>{{ region }}</h2>
    </header>
    <nav>
      <img id="kropotkin" src="{% static "classifieds/images/kropotkin.jpg" %}" alt="the face of peter kropotkin done in a woodblock style"></img>
      <h1><a href="{% url 'classifieds:index' %}">Breadlist</a></h1>
      <p><a href="{% url 'classifieds:create_classified' %}">create a classified</a></p>
      <ul>{% for p in page_list %}
        <li id={{ p }}><a href="{% url 'classifieds:page' p.page_name %}">{{ p }}</a></li>{% endfor %}
      </ul>
    </nav>
    <main>{% for p in province_list_sorted %}
      <section>
        <li><a href="{% url 'classifieds:province' p.id %}">{{ p }}</a></li>
      </section>{% endfor %}
    </main>
    <aside>
      <ul>{% for r in region_list %}
        <li class="sidebar-locale"><a href="{% url 'classifieds:region' r.id %}">{{ r }}</a></li>{% endfor %}
      </ul>
    </aside>
    <footer>
      <ul>
        <li><a href="{% url 'classifieds:index' %}">breadlist</a></li>
      </ul>
    </footer>
  </body>
</html>

classifieds/templates/classifieds/section-index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Breadlist: {{ section }} in {{ locale }}</title>{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'classifieds/style.css' %}">
  </head>
  <body>
    <header>
      <h2><a href="{% url 'classifieds:locale' locale.id %}">{{ locale.locale_name }}</a></h2>
      <h3>{{ section }}</h3>
    </header>
    <nav>
      <img id="kropotkin" src="{% static "classifieds/images/kropotkin.jpg" %}" alt="the face of peter kropotkin done in a woodblock style"></img>
      <h1><a href="{% url 'classifieds:index' %}">Breadlist</a></h1>
      <p><a href="{% url 'classifieds:create_classified' %}">create a classified</a></p>
      <ul>{% for p in page_list %}
        <li id={{ p }}><a href="{% url 'classifieds:page' p.page_name %}">{{ p }}</a></li>{% endfor %}
      </ul>
    </nav>
    <main>{% if section_classified_list %}
      <ul>
      {% for c in section_classified_list %}
          <li><a href="{% url 'classifieds:detail' c.id %}">{{ c.subsection }}: {{ c }}</a></li>{% endfor %}
      </ul>{% else %}
      <p>No classifieds are available.</p>{% endif %}
    </main>
    <aside>
      <ul>{% for r in region_list %}
        <li class="sidebar-locale"><a href="{% url 'classifieds:region' r.id %}">{{ r }}</a></li>{% endfor %}
      </ul>
    </aside>
    <footer>
      <ul>
        <li><a href="{% url 'classifieds:index' %}">breadlist</a></li>
        <li><a href="{% url 'classifieds:region' locale.region_id %}">breadlist/{{ locale.region }}</a></li>
        <li><a href="{% url 'classifieds:province' locale.province_id %}">breadlist/{{ locale.region }}/{{ locale.province }}</a></li>
        <li><a href="{% url 'classifieds:locale' locale.id %}">breadlist/{{ locale.region }}/{{ locale.province }}/{{ locale }}</a></li>
      </ul>
    </footer>
  </body>
</html>

classifieds/templates/classifieds/subsection-index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Breadlist: {{ section }} {{ subsection}} in {{ locale }}</title>{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'classifieds/style.css' %}">
  </head>
  <body>
    <header>
      <h2><a href="{% url 'classifieds:locale' locale.id %}"> {{ locale.locale_name }} </a></h2>
      <h3><a href="{% url 'classifieds:section' locale.id section %}"> {{ section }}: </a></h3>
      <h4>{{ subsection }}</h4>
    </header>
    <nav>
      <img id="kropotkin" src="{% static "classifieds/images/kropotkin.jpg" %}" alt="the face of peter kropotkin done in a woodblock style"></img>
      <h1><a href="{% url 'classifieds:index' %}">Breadlist</a></h1>
      <p><a href="{% url 'classifieds:create_classified' %}">create a classified</a></p>
      <ul>{% for p in page_list %}
        <li id={{ p }}><a href="{% url 'classifieds:page' p.page_name %}">{{ p }}</a></li>{% endfor %}
      </ul>
    </nav>
    <main>{% if subsection_classified_list %}
      <ul>{% for c in subsection_classified_list %}
          <li><a href="{% url 'classifieds:detail' c.id %}">{{ c }}</a></li>{% endfor %}
      </ul>{% else %}
    <p>No classifieds are available.</p>{% endif %}
    </main>
    <aside>
      <ul>{% for r in region_list %}
        <li class="sidebar-locale"><a href="{% url 'classifieds:region' r.id %}">{{ r }}</a></li>{% endfor %}
      </ul>
    </aside>
    <footer>
      <ul>
        <li><a href="{% url 'classifieds:index' %}">breadlist</a></li>
        <li><a href="{% url 'classifieds:region' locale.region_id %}">breadlist/{{ locale.region }}</a></li>
        <li><a href="{% url 'classifieds:province' locale.province_id %}">breadlist/{{ locale.region }}/{{ locale.province }}</a></li>
        <li><a href="{% url 'classifieds:locale' locale.id %}">breadlist/{{ locale.region }}/{{ locale.province }}/{{ locale }}</a></li>
        <li><a href="{% url 'classifieds:section' locale.id section.section_name %}">breadlist/{{ locale.region }}/{{ locale.province }}/{{ locale }}/{{ section }}</a></li>
      </ul>
    </footer>
  </body>
</html>

classifieds/templates/classifieds/thanks.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Thanks</title>{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'classifieds/style.css' %}">
  </head>
  <body>
    <header>
      <h2>Thanks</h2>
    </header>
    <nav>
      <img id="kropotkin" src="{% static "classifieds/images/kropotkin.jpg" %}" alt="the face of peter kropotkin done in a woodblock style"></img>
      <h1><a href="{% url 'classifieds:index' %}">Breadlist</a></h1>
      <p><a href="{% url 'classifieds:create_classified' %}">create a classified</a></p>
      <ul>{% for p in page_list %}
        <li id={{ p }}><a href="{% url 'classifieds:page' p.page_name %}">{{ p }}</a></li>{% endfor %}
      </ul>
    </nav>
    <main>
      <p>thanks for posting!</p>
      <p>{{ form }}</p>
    </main>
    <aside>
      <ul>{% for r in region_list %}
        <li class="sidebar-locale"><a href="{% url 'classifieds:region' r %}">{{ r }}</a></li>{% endfor %}
      </ul>
    </aside>
    <footer>
      <li><a href="{% url 'classifieds:index' %}">breadlist</a></li>
    </footer>
  </body>
</html>